name: Acquire activation file
on: # <-- 2行目。on:は行頭から始める
  workflow_dispatch: {} # <-- on: の下はスペース2つでインデント

jobs: # <-- 行頭から始める
  activation: # <-- jobs: の下はスペース2つでインデント
    name: Request manual activation file
    runs-on: ubuntu-latest
    steps: # <-- activation: の下はスペース4つでインデント
      - name: Request manual activation file # <-- steps: の下はスペース6つでインデント
        id: getManualLicenseFile
        uses: game-ci/unity-request-activation-file@v2
        with:
          # あなたのプロジェクトのUnityバージョンに合わせる
          unityVersion: 6000.2.2f1 
      - name: Expose as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.getManualLicenseFile.outputs.filePath }}
          path: ${{ steps.getManualLicenseFile.outputs.filePath }}
